name: MathBloom
options:
  bundleIdPrefix: com.haebom
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

settings:
  base:
    INFOPLIST_KEY_CFBundleDisplayName: "산수해봄"
    INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.education"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    SWIFT_EMIT_LOC_STRINGS: YES

targets:
  MathBloom:
    type: application
    platform: iOS
    sources:
      - path: MathBloom
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.haebom.mathbloom
        DEVELOPMENT_TEAM: TFTZ3B7PCX
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: NO

  MathBloomTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: MathBloomTests
    dependencies:
      - target: MathBloom
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.haebom.mathbloom.tests
